In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression

In [ ]:
df=pd.read_csv('/content/house_price_regression_dataset.csv')
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [ ]:
x=df.drop('House_Price',axis=1)

In [ ]:
x

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8
...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10
996,3179,1,2,1999,2.977123,1,10
997,2606,4,2,1962,4.055067,0,2
998,4723,5,2,1950,1.930921,0,7
999,3268,4,2,1983,3.108790,2,2

In [ ]:
y=df.House_Price

In [ ]:
y

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([ 420016.45662314,  889705.15941309,  761608.6430324 ,
        503189.80766365,  503466.10915197,  295341.42772613,
        607200.98247049,  554436.32610969,  860304.52967329,
        614036.12441298,  931033.69403694,  862209.05713148,
        218355.39278026,  187061.01463297,  302925.71820609,
        154898.97192993,  751803.63129168,  942430.65571495,
        265344.29973938,  576679.4016093 ,  488091.40012344,
        378981.41604731,  836873.27596005,  403986.56816581,
        945312.93099419,  819603.34667094,  391816.38226315,
        963111.64124643,  517382.78413005,  383247.28778344,
        372586.37197792,  771054.66820169,  476459.31498383,
        688448.45838577,  320614.3002649 ,  525103.57345025,
        654473.02319023,  882574.05198663,  238224.15385798,
        951370.63844527,  747158.48573118, 1103534.12487697,
        419591.66005717,  226562.99209483,  661398.58445183,
        522086.07414668,  187887.85575882,  365812.60667008,
        799558.47294548,  732465.20702576,  349170.7090038 ,
        549904.89769467,  756469.84004251,  247576.26072673,
        681163.32696046,  317307.01266488,  759692.83413552,
        553752.81258509,  709256.53307862,  277921.40193899,
        303393.31343808,  466017.18499425,  721503.30431472,
        181342.2805746 ,  697152.61013497,  911202.04695017,
       1016601.61305497,  803397.4660051 ,  529889.54609403,
        845958.91066756,  215759.98856779,  403127.33660236,
        691527.17897894,  486211.55665285,  853200.64152532,
        926650.61577895, 1025347.28840141,  653169.44959467,
        616829.96065765,  730836.14089394,  673713.25788188,
        579907.66024678,  851815.24336412,  832545.06068864,
        557237.21358787,  929925.46121096,  426949.79363148,
        613277.17256703, 1058733.34253086,  909388.19866292,
        812500.28550623,  677317.32031959,  743744.97200358,
       1050586.83294772,  403276.75565758,  513897.32774955,
        974439.67400148,  927934.86856575,  815261.65537207,
        428462.44918158,  994098.66012274,  835976.14249796,
        697653.36051462,  878478.44755729,  306619.70475774,
        326812.8591771 ,  745754.63679615,  487564.22397957,
        673250.1202422 ,  787042.73606105,  608158.77866479,
        885788.89371648,  581128.93497295,  645347.79075823,
        308767.76687776, 1083506.57292476,  845311.72080695,
        222846.47847817,  699290.41702852,  877533.39551451,
        841836.60909411,  930059.71691329,  189848.07649486,
        636550.51191454,  814645.68370741,  863031.83557951,
        549490.6261849 ,  630302.13232003,  676093.86112051,
        152150.21745261,  834392.61405384,  711375.25867475,
        260579.18821632,  675681.51268671,  773042.22846463,
        626289.15751969,  787776.55984147,  540199.60871856,
        184850.74589489,  237443.43317144,  843894.62670784,
       1035837.5597443 ,  244891.66258077,  877078.1711938 ,
        507430.44582925,  737313.23305125,  783233.41003549,
        324028.32920466,  617268.2736762 ,  204943.45861281,
        624449.89141935,  546489.36914657,  217806.9605222 ,
        182910.71357568,  864245.10638782,  267167.98426863,
        444984.75850544,  309802.81430466,  646030.57808161,
        857370.26734323,  770395.48500994,  594677.06329496,
        603462.56951208,  655893.27121204,  509125.88762134,
        728415.97207979,  583463.33891192,  979200.23995694,
       1025604.72591178,  732330.70012925,  719559.78084039,
        350940.80531427,  539402.55529435,  908294.55776845,
        802338.46240982,  534666.87834219,  505167.5323482 ,
        293011.93150165,  271934.96787116,  691995.06486337,
        469234.05670183,  727014.80193019,  356182.20223255,
        470016.77568828,  980998.79564969,  509043.92079579,
        838106.41224781,  383315.22167499, 1006650.98184915,
        995774.35769421,  755993.67826877,  430579.79275155,
        363889.19210137,  436888.26546316,  218920.37030778,
        615639.39685281,  786310.4144312 ,  348704.20274972,
        421031.46314364,  662242.54516407,  856430.89808988,
        620072.18508279,  660322.67185218,  868805.9051372 ,
        548145.20502427,  654808.84178784,  195990.61862061,
        737084.60726513,  453554.98167291,  801600.64984469,
       1024309.32657415,  759376.747078  ,  173347.37561137,
        373243.40708335,  814270.39472073,  331457.5422192 ,
        303442.79265905,  399835.00505032,  724526.29421738,
        754595.02352213,  589557.45791649,  840873.58966133,
        890297.05689651,  970461.42750622,  694307.29293859,
        232221.93818992,  461714.52782597,  863195.8932275 ,
        543190.32310932,  337239.07689873,  650756.31121972,
        730226.03584109,  742808.62410523,  692744.16643258,
        858651.0127722 ,  588570.41580028,  365692.15785405,
        733509.07153301, 1012342.99985868,  580216.48407883,
       1046931.26928909,  560983.4347957 ,  685015.2841791 ,
        258235.17790295,  559080.49451308,  708528.38510022,
        245535.19729293,  687110.18370789,  976059.32587444,
        818007.67533716,  347846.40540134,  454458.19326075,
        350007.41116569,  531864.7220471 ,  304178.09983416,
        833850.8516907 ,  435290.21325802,  266150.23549645,
        669139.57524684,  715652.92136391,  515866.62711021,
       1018908.07511431,  509759.97842758,  615536.58072371,
        831115.1034821 ,  419163.25483146,  314873.20224004,
        728388.65164069,  776667.28570417,  897173.46365394,
        771513.0444546 ,  934517.02959825, 1020386.89269836,
        985916.66786158,  137144.20157931,  243889.9420117 ,
        357865.05947634,  844570.15189586,  580634.68436886,
        577993.1474291 ,  773352.38376069,  951680.23168604,
        628298.90874763, 1012810.17766223,  866053.90182604,
       1028796.97800621, 1029642.99516923, 1084200.73610226,
        624132.1837086 ,  342165.21390308,  593143.39714464,
        281899.68813849,  933226.47819709,  627715.7918943 ,
       1025819.25088728,  482537.99990477,  246212.68011424,
        460752.73671802,  980096.06142094,  306228.57600454])

In [ ]:
model.score(x_test,y_pred)

1.0

In [ ]:
r2_score(y_pred,y_test)

0.9980835054702915

In [ ]:
mean_absolute_error(y_pred,y_test)

8767.742664039077

In [ ]:
mean_squared_error(y_pred,y_test)

116087637.42025527